version: "3.9"

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: classes_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: classes
      POSTGRES_USER: classes_user
      POSTGRES_PASSWORD: classes_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
